frontend/src/components/Buttons/Buttons.js, frontend/src/components/Buttons/CloseButton.js, frontend/src/components/Cards/Cards.js, frontend/src/components/Carousel/ClickCarousel.js, frontend/src/components/Carousel/ScrollCarousel.js, frontend/src/components/Navigation/HeaderNav.js, frontend/src/components/Navigation/InnerCopNav.js, frontend/src/index.scss
This is a quick fix for an import bug that has been causing class overriding to not work as intended.
- Moved all imports from individual js files to `index.scss`
=> fixed repeated import bug

app/frontend/src/assets/images/images.js, app/frontend/src/pages/Demo/Demo.js, app/frontend/src/pages/LandingPage/LandingPageCop.js, app/webpack.config.js, mkdocs/docs/developer/design-system.md
Fixes #230
- Added svgWrapper function inside of `image.js` redirection file to add accessibility text to SVG components
- Edited import wording slightly so enable effective wrapping without breaking existing code. Wrapped import names are now appended with P (for pre-wrapped) at the end
- Configured webpack to allow for accessibility props
- Edited currently used svgs for accessibility
- Small changes to docs
=> Build accessibility text  into inline svgs

app/frontend/src/components/Navigation/ProgressBar.tsx, app/frontend/src/components/Navigation/_ProgressBar.scss, app/frontend/src/components/Navigation/_index.scss, app/frontend/src/components/components.tsx, app/frontend/src/pages/Demo/Demo.tsx, app/package-lock.json, app/requirements.txt, app/tests/components/ProgressBar.test.js
Fixes #275  
- created `<ProgressBar>` component which uses a div with roles set as progress bar
- the browser's native `<progress>` element could not be tuned to fit our design system of having separate bars 
- upgraded dependencies for both react and python side
- added new component to demo
- added new accessibility tests for progress bar
=> Created progress bar component

.github/workflows/build-deploy-stage.yml
Fixes #379
- Updated `aws-actions/configure-aws-credentials` from `v1` to `v2`
- Both the node version and `set-output` warning occur during the `Configure AWS credentials` step that uses `configure-aws-credentials@v1`
- I'm not sure how to find a migration guide but the [recent updates section](https://github.com/aws-actions/configure-aws-credentials#recent-updates) of `configure-aws-credentials` README explains 
> We've recently released a v2 of this action that uses the Node 16 runtime by default. You should update your action references to v2... When migrating to v2, you don't have to consider any changes other than the node version. There are no breaking changes between versions; As of release of v2, the node version is the only change.
=> Update configure-aws-credentials to v2

.pre-commit-config.yaml, dev/linter.dockerfile
Fixes #147
- Added prettier hook to the `.pre-commit-config.yaml` file as recommended by [option 3 from the Prettier documentation](https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit) because I think it best fits our use case of working with a multi-language project
- Chose `v2.7.1` as it seems to be the latest stable version of prettier supported by the [mirrors-prettier repo](https://github.com/pre-commit/mirrors-prettier) that the Prettier docs recommend using
- Added `nodejs` and `npm` to apk dependencies in `linter.dockerfile` because prettier requires them or else `docker compose build linter` will fail
-  Rebuild linter image with `docker compose build linter`
- Disable prettier on save if you have that configured and then mess up the …
=> Add pre-commit hook for prettier

alias-config.txt, alias.sh, mkdocs/docs/developer/devops.md, mkdocs/docs/developer/installation.md
Fixes #192
- Added shell script `alias.sh` that leverages the `alias-config.txt` file allowing us to create shortened versions of longer shell commands and run them like `./alias.sh test`
- Populated `alias-config.txt` with as many commands as I could find from our mkdocs
- You will most likely need to give the script file permission to execute with a command like `chmod u+x alias.sh` if you want to run script with `./alias.sh start` , but you might be okay to use `bash ./alias.sh start` without modifying permissions
- While researching, I was warned that not all operating systems ship with the `script` command installed by default.
-  The trade off is that if we use `eval "$command"` instead then we will have to add `-T` option to `docker run` commands in the `alias-config.txt` file …
=> Bash script for aliases

docker-compose.yml
Fixes #411 
- Added a volume within the `webpack` service that points to the newly created named volume `node_modules` that sits at the root level of the `docker-compose.yml` file so that the necessary node packages will now persist inside of the `webpack` container
- The `webpack` container no longer exits with an error
- For the fix to work you will need to run `docker compose build --no-cache` while on my branch. Then run `docker compose up`
[GPT4 conversation](https://chat.openai.com/share/5a6325ba-e50a-4c79-acf4-785590fe7476)
The `webpack` container was exiting with the following error
```
[ CivicTechJobs ] $ docker logs 2d14073c954db70485b03e6f69ca2de7829a0d64994185aad0ead6b66ca902b8
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /code/package.json
npm ERR! errno -2
npm …
```
=> Fixing local development environment

backend/pyproject.toml
Reverts #431
The `Build, push image to ECR and deploy to ECS` job is still failing and has an additional error related to the pyyaml version after merging #431 
```
#20 2.767 Because backend depends on pyyaml (^6.0.1) which doesn't match any versions, version solving failed.
```
https://github.com/hackforla/CivicTechJobs/actions/runs/5906751481/job/16023388193#step:5:214
=> Revert "update pyyaml version"

frontend/src/components/Buttons/_Button.scss, frontend/src/pages/Demo/DemoTailwind.tsx, frontend/tailwind.config.js
Fixes #429
- Added:
- customized colors found in _colors.scss
- customized screens found in _breakpoints.scss for responsive designs
- customized font family
- Extended:
- line height
- border radius (for buttons) 
- Demonstrated on /demo-tailwind page:
- buttons
Problem--needs discussion:
Currently, we imported 
`import "tailwindcss/tailwind.css";
import "./index.scss";` in such order so that tailwind styles don't override existing components styled with Sass. However, some Sass classes share the same names (e.g. p for padding) but have different values. For example, p-1 in our Sass is `padding: 8px;` but in tailwind p-1 is `padding: 0.25rem; /* 4px */` and because of this, new components relying on TW classes can't use p1-p6 to get TW styles. I think we would either need to do some …
=> Customized and extended tailwind styles

dev/django.dockerfile, stage/Dockerfile
Fixes #457 
- Specify version of poetry to download at 1.3.0 as detailed [here](https://github.com/python-poetry/poetry/issues/7611)
=> Bug causing deployment to fail with Poetry version > 1.3.0

dev/django.dockerfile, stage/Dockerfile
Fixes #457 
- Revert poetry version to 1.3.0
- Disabled checks causing lint errors
=> 457 deployment bug in staging

frontend/src/components/Inputs/Calendar.tsx, frontend/tests/components/Calendar.test.tsx
Fixes #301 
- Added a data test id for calendar
Unit Tests
- Calendar Renders
- Accessibility labels are applied // *test created based off of ProgressBar.test.tsx*
Integration Tests
- Able to select and unselect availability
=> Added jest tests for calendar component

stage/Dockerfile
Fixes #457
- Added `postgresql-dev` to the dockerfile that build image used for staging site deployment
- I think the root of problem is that `pg_config` cannot be found and GPT thinks that installing `postgresql-dev` as part of the image building process will make `pg_config` available
=> Attempt fix for staging deployment

.github/workflows/mkdocs-build.yml
Fixes #456
- updated python setup action version 
- fixed python version to 3.9 based on advice from docs
- combined `cd` operations to make deploy script less confusing
- https://chat.openai.com/share/b9a11492-1029-401c-a93e-05fbef0e7295
- https://github.com/actions/setup-python
=> Fix mkdocs deployment

.github/workflows/mkdocs-build.yml
Reverts hackforla/CivicTechJobs#477
Mkdocs deployment not fixed by #477
- https://github.com/hackforla/CivicTechJobs/actions/runs/6792090853/job/18464792012
=> Revert "Fix mkdocs deployment"

.github/linters/.stylelintrc.json, .github/workflows/linter.yml, mkdocs/docs/developer/frontend.md
Fixes #456
- Added __init__.py file in mkdocs-config folder
- updated frontend.md to reflect current frontend stack and for testing
=> Attempt to fix mkdocs deployment bug

.github/workflows/mkdocs-build.yml
Fixes https://github.com/hackforla/CivicTechJobs/issues/456
Changes
- Uses Markdown 3.2.0.
=> Rollback markdown to v3.2.0

frontend/src/api_data/copData.ts, frontend/src/context/QualifiersContext.tsx, frontend/src/pages/QualifierPage/QualifierPage.tsx, frontend/src/pages/QualifierPage/QualifierPageCalendar.tsx, frontend/src/pages/QualifierPage/QualifierPageRoles.tsx, mkdocs/docs/developer/frontend.md
Fixes #500 
- Designed JSON structure for COP qualifiers
- Created context for the  qualifiers/1 (COPs and roles within each COP), and refactored QualifiersPageRoles page
- Added documentation for COP qualifiers JSON structure in mkdocs
<details>
<br>
<br>
</details>
=> Created Context for Qualifier 1 Page 

backend/api/settings.py, backend/api/urls.py, backend/ctjbackend/apps.py, backend/ctjbackend/uptime.py, backend/ctjbackend/urls.py, backend/ctjbackend/views.py
Fixes #523
- Configured api urlpatterns to include ctjbackend.
- Created Healthcheck View that returns JSON that includes application uptime, a healthcheck message, and version.
- Created healthcheck path in ctjbackend urlpatterns
=> Add healthcheck api for new backend

backend/backend/settings.py, docker-compose.yml
- Changed localhost to db in setting.py
- docker compose:
- Specified postgres version
- Added restart on-failure to backend
- Added a healthcheck for db as a depends-on condition for backend
I'm not sure if the healthcheck as a depends-on condition is necessary or is the best solution to make sure the db is running first for the backend to connect to. However, without it, restart: on-failure doesn't seem to consistently work for me.
=> Configured docker compose

docker-compose.dev.yml
Fixes #
Issue:
In the `docker-compose.dev.yml`, there was no healthcheck for the postgres db container to make sure it's working before starting the django container.
- Jimmy quote from 09/05/24 meeting: "django needs a restart clause to make sure postgres container is ready"
- [depends\_on doesn't wait for another service in docker-compose 1.22.0 - Stack Overflow](https://stackoverflow.com/questions/52699899/depends-on-doesnt-wait-for-another-service-in-docker-compose-1-22-0)
- Used this link to help create the docker-compose file: [Dockerizing Django with Postgres, Gunicorn, and Nginx | TestDriven.io](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/)
This PR should fix it.
How to test:
Start the application in dev mode from my `feat/vite-hmr` branch:
```sh …
```
=> Added pgdb healthcheck to the docker-compose.dev.yml

backend/backend/settings.py, backend/ctj_api/urls.py, backend/ctj_api/views.py
Fixes #523 
Just want to quickly resolve and close this issue already.
You can test by going to `http://localhost:8000/api/healthcheck`
- Basically copied the code from Bitian's PR here: https://github.com/hackforla/CivicTechJobs/pull/547
- and added a property for `hostname` in the json response
Looks like Bitian's code was accidentally removed when Jimmy was initializing a new backend in this commit: https://github.com/hackforla/CivicTechJobs/commit/b28bdba05ed0f9121e9dbdce64e621ef00c1506e
=> Feature: Add healthcheck api endpoint for new backend

mkdocs/docs/resources.md
Fixes #
As a team member, I would like to have one page in the docs that lists every resource I could possibly need, so that I don't get lost trying to find a specific doc I am looking for.
https://hackforla.github.io/CivicTechJobs/resources/
- Updated resources page in the docs
=> Update Resources page in docs

backend/ctj_api/admin.py, backend/ctj_api/models.py, backend/ctj_api/serializers.py
Fixes # 614
- Added models for Communities of Practice, Roles, Skills, and Projects
- Added serializer for the models mentioned above
- Checked list of tables in pgdb container to make sure these new tables are shown
=> Added models and serializers for COP, roles, skills and project

backend/ctj_api/permissions.py
`test_create_opportunity_as_regular_user` returned 201 instead of 403, so I tried updating the OpportunityPermission to enforce stricter rules for POST, PUT, and DELETE.
- permissions.py
=> Update Opportunity Permisson

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Demo/DemoTailwind.tsx, frontend/src/tw-components/Buttons.tsx, frontend/tailwind.config.js
- Created button components using Tailwind based on this [Figma design](https://www.figma.com/design/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=12354-1711&t=jvOt1A8v42lzmupy-0)
- Added buttons to `/demo-tailwind` page to showcase enabled, disabled, hover, focus, and active effects
- Added a "Toggle Dark Mode" button to `/demo-tailwind` page to switch between light and dark mode for testing
<details>
<summary>Light Mode</summary>
<br>
<br>
</details>
<details>
<summary>Dark Mode</summary>
<br>
<br>
</details>
=> Added Tailwind Button Components

.github/workflows/deploy-dev.yml
Added ver.1 of the github action, this action pushes a public image from dockerhub and will attempt to verify that the CICD pipeline to incubator is working
- adds develop-dev.yml to github actions
- Does not push the application image, but rather a public dockerhub image 
- Once pipeline to confirmed, will update to use our application image and call ECS
=> Adding Github action to push container to ECR through the Incubator CICD 

.github/workflows/deploy-stage.yml
Fixes #
- renamed `deploy-dev.yml` github action file to `deploy-stage.yml`
- excluded mkdocs and dev folder paths so the action does not run on changes to files in those folders.
=> Deploy-stage: rename github action and exclude paths

mkdocs/docs/developer/devops.md, mkdocs/docs/developer/installation.md, mkdocs/docs/developer/quickstart-guide.md, mkdocs/docs/index.md, mkdocs/mkdocs.yml
Fixes #
Added my notes about how to quickly start up various environments on your local machine to docs. I believe it will be useful for team members.
Added documentation about 
- how to run dev and stage environments with and without docker
- How to run mkdocs dev server
- How to create django admin credentials
- how to lint the backend
=> Documentation: Add quickstart environments guide

README.md
Fixes #272
- updated tech stack list in readme
- include typescript
=> Update readme: update tech stack list
