hackforla/CivicTechJobs

.github/ISSUE_TEMPLATE/blank-issue-form.yml, .github/workflows/issue-trigger.yml, .github/workflows/sortOpenedIssues/config.json
Fixes #56
- Added GHA that will sort newly created issues
- Uses a GHA module from my personal repository. The goal for that GHA is to port it over to 100automations in the future
- Also edited our form template so that the GHA can work better
None
=> added gha to sort issues

frontend/src/components/Basics/_breakpoints.scss, frontend/src/components/Basics/_index.scss, frontend/src/index.scss
Fixes #71 
- Added breakpoint mixins
- To use, use sass syntax @include breakpoint-media-min($device)
- updated demo to change text colors responsively
No screenshots
=> Added breakpoints

frontend/src/components/Basics/_colors.scss, frontend/src/components/Basics/_index.scss, frontend/src/index.scss
Fixes #62
- Added the colors shown on the Design System in Figma
- Changed frontpage demo to showcase how to use colors
No screenshots
=> Added color palette

frontend/src/components/App.js, frontend/src/components/Basics/_index.scss, frontend/src/components/Basics/_typography.scss
Fixes #63
- added title-* classes according to Figma
- added paragraph-* classes according to Figma
- changed front page to showcase classes
No screenshots
=> added typography

frontend/src/components/_normalize.scss, frontend/src/index.scss
Fixes #97
- Added normalize.css from [here](https://necolas.github.io/normalize.css/latest/normalize.css) as _normalize.scss
No screenshots
=> added normalize.scss

frontend/src/components/App.js, frontend/src/components/Basics/_alignment.scss, frontend/src/components/Basics/_index.scss, frontend/src/index.scss
Fixes #69
- Added text alignment classes in _aligment.scss
No screenshots
=> added text alignment

frontend/src/components/Basics/_typography.scss
close #114 
- Changed front sizing to rem units
=> converted font sizes from px to rem.

webpack.config.js
Fixes #
- Adds a Favicon to the website
=> Add favicon 

package-lock.json, package.json
This is a PR to add react router ahead of #132 since changes to package-json/package.json breaks super-linter
- 
- 
-
=> added react router

.github/ISSUE_TEMPLATE/blank-issue-form-d.yml, .github/ISSUE_TEMPLATE/component-issue-form.yml
=> added and updated new issue forms

frontend/src/components/Navigation/HeaderNav.js, frontend/src/components/Navigation/_HeaderNav.scss, frontend/src/pages/landingPage/_landingPage.scss, frontend/src/pages/landingPage/landingPage.js
This is a quick fix for a header bug which caused elements to go behind it. To fix, a dummy div is added behind the header which pushes everything down.
- Fixed header bug with dummy div element
- Readjusted landing page to ensure that the visual appearance of the website did not change
=> Update header with hidden div to push elements down

CONTRIBUTING.md, mkdocs/mkdocs.yml
=> corrected documentation links

app/frontend/src/components/Basics/_colors.scss, app/frontend/src/components/Basics/_typography.scss, app/frontend/src/components/Cards/CircleCard.js, app/frontend/src/components/Cards/_CircleCard.scss, app/frontend/src/components/Cards/_index.scss, app/frontend/src/components/Navigation/InnerCopNav.js, app/frontend/src/components/components.js, app/frontend/src/index.scss, app/frontend/src/pages/Demo/Demo.js, app/frontend/src/pages/Demo/_Demo.scss
Fixes #64
- created circle card component, which has "sm" or "lg" choices for the size prop
- cleaned up some imports from `InnerCopNav.js`
- updated Demo page to showcase usage of new component
- created responsive mixin for circle card
=> Circle cards component

.github/ISSUE_TEMPLATE/blank-issue-form-d.yml, .github/ISSUE_TEMPLATE/blank-issue-form.yml, .github/ISSUE_TEMPLATE/component-issue-form.yml, CONTRIBUTING.md, mkdocs/docs/developer/installation.md, mkdocs/docs/joining-the-team/content-writer.md, mkdocs/docs/joining-the-team/data-scientist.md, mkdocs/docs/joining-the-team/intro.md, mkdocs/docs/joining-the-team/other-volunteer.md, mkdocs/docs/joining-the-team/product-manager.md, mkdocs/docs/joining-the-team/uiux-designer.md, mkdocs/docs/joining-the-team/uiux-researcher.md, mkdocs/docs/joining-the-team/web-developer.md, mkdocs/docs/misc/ada-guide.md, mkdocs/docs/misc/glossary.md, mkdocs/docs/misc/history.md, mkdocs/docs/misc/our-process.md, mkdocs/docs/misc/research-wiki-template.md, mkdocs/docs/misc/security-updates.md, mkdocs/docs/misc/the-team.md, mkdocs/docs/resources.md, mkdocs/mkdocs.yml
Fixes #165 
- Migrated all wiki files to mkdocs
- Replaced all links to wiki with documentation site link
- Still awaiting approval for editing wiki front page
=> Mkdocs migration

mkdocs/Dockerfile, mkdocs/mkdocs-config/mkdocs-config.py, mkdocs/mkdocs-config/setup.py, mkdocs/mkdocs.yml
This is a quick fix for a bug.
- Fixed prettier causing incorrect rendering of MkDocs nested lists through a support extension.
- Slightly adjusted headers
-
=> Fix formatting of mkdocs

app/frontend/src/assets/images/svgs/landing-page-bg.svg, app/frontend/src/components/Basics/_layout.scss, app/frontend/src/pages/LandingPage/LandingPageCop.js, app/frontend/src/pages/LandingPage/LandingPageIntro.js, app/frontend/src/pages/LandingPage/_LandingPageCop.scss, app/frontend/src/pages/LandingPage/_LandingPageIntro.scss, app/tests/pages/LandingPage.test.js
Fixes #163 
Fixes #226
- added flex-column class which differs from flex-container in that it uses column for flex-direction
- updated CSS on `LandingPageCop.scss` to mesh better with new background image
- updated styling on `LandingPageIntro.scss` to include new background, and removed intuitive properties such as negative margins and relative positioning
- added new tests to test landing page dialog
=> Added new landing bg image and fixed bug

app/frontend/src/components/Basics/_typography.scss, app/frontend/src/index.scss
=> changed font-family for title, body,paragraph

app/frontend/src/assets/images/images.tsx
resolves #296 
- added descriptions to the 13 svg images in `images.tsx`.
=> Svg descriptions redo 1

app/frontend/src/pages/QualifierPage/QualifierPage.tsx, app/frontend/src/pages/QualifierPage/QualifierPageCalendar.tsx, app/tsconfig.json, app/webpack.config.js
resolves #50 
- `QualifierPage` => lazy loading added for `calendar` component. the fallback component doesn't look great YET, but I think that we can tackle that next or later? Don't feel it's urgent. Thoughts?
- `QualifierPageCalendar.tsx` - setting up the component for lazy loading by exporting it by default
- `tsconfig` => replaced `tsconfig module` with `esnext`, previously was set to `commonJS`. `commonJS` is not compatible with lazy loading, nor is it compatible with tree-shaking, unlike `esnext`, hence the change
- `webpack-config` => added a flag that enables tree shaking
=> Webpack improvements redo 1

app/server/tests.py, app/server/urls.py, app/server/views.py
Part of #159 and #78
- Added healthcheck endpoint /api/healthcheck to pass ECS healthchecks
=> add healthcheck endpoint

.github/workflows/build-deploy-stage.yml, stage/Dockerfile
- Pin python alpine image to specific version
=> lint ignore stage Dockerfile

app/package-lock.json, app/requirements.stage.txt, app/requirements.txt
Fixes [Security issues](https://github.com/hackforla/CivicTechJobs/security/dependabot).
-
-
-
=> updated npm and pip dependencies

.github/workflows/build-deploy-stage.yml
Fixes #
- Quick fix to an error in [migrating github outputs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) 
-
-
=> corrected output bug

app/requirements.stage.txt
=> added missing dependency

app/frontend/src/components/Navigation/FooterNav.tsx, app/frontend/src/components/Navigation/_FooterNav.scss
Fixes #261 
- In app/frontend/src/components/Navigation/FooterNav.tsx: Added a class .logo-anchor to the <a> element that has a child logo <img> in the Footer
- In app/frontend/src/components/Navigation/_FooterNav.scss added styles for class .logo-anchor and set the display to block
- Before:
<details>
<summary>Screenshot</summary>
<br>
<br>
</details>
- After:
<details>
<summary>Small Screen</summary>
<br>
<br>
</details>
<details>
<summary>Medium Screen</summary>
<br>
<br>
</details>
<details>
<summary>Large Screen</summary>
<br>
<br>
</details>
=> Adjusted logo anchor display for tabfocus

app/frontend/src/components/Basics/_layout.scss, app/frontend/src/components/Basics/_spacing.scss
Fixes #126
- Added gap utilities in app/frontend/src/components/Basics/_spacing.scss
=> Add gap utilities 126

.github/pull_request_template.md, .github/workflows/build-deploy-stage.yml, app/frontend/src/components/Buttons/Button.tsx, app/frontend/src/components/Navigation/FooterNav.tsx, app/frontend/src/components/Navigation/HeaderNav.tsx, app/frontend/src/pages/Demo/Demo.tsx, app/frontend/src/pages/LandingPage/LandingPage.tsx, app/frontend/src/pages/LandingPage/LandingPageCop.tsx, app/frontend/src/pages/LandingPage/LandingPageIntro.tsx, app/frontend/src/pages/NotFoundPage/NotFoundPage.tsx, app/frontend/src/pages/QualifierPage/QualifierPage.tsx, app/frontend/src/pages/QualifierPage/QualifierPageCalendar.tsx
Partial fix for #78
- This is a partial fix for #78
- Since our staging website is already up, I have decided to do a quick PR to fix a lot of unfortunate bugs such as:
- urls leading to the wrong page  
- security vulnerabilities with our `<a>` tags
- the staging env being hosted in debug mode
=> Corrected links and added debug to aws env

.github/workflows/build-deploy-stage.yml
Fixes #
-
-
-
<details>
<br>
<br>
</details>
=> added back localhost which is used for healthcheck endpoint

.github/workflows/jest-react-test.yml
Fixes #
- This fix will allow us to add jest to branch protection with a useful sounding name
- Related [stackoverflow](https://stackoverflow.com/questions/69177488/how-to-set-github-actions-as-required-status-checks)
-
<details>
<br>
<br>
</details>
=> Added name to jest action

frontend/src/components/Navigation/FooterNav.tsx
Fixes #416
- Updated link to Credits Page
=> Updated link to Credits Page in Footer

backend/pyproject.toml
#430 
- just a quick test to update to the latest pyyaml in pytoml. Not sure why it isn't getting pulled during build.
-
-
=> fixed pr by making a new one

dev/django.dockerfile, stage/Dockerfile
Reverts hackforla/CivicTechJobs#458
=> Revert "Bug causing deployment to fail with Poetry version > 1.3.0"

dev/django.dockerfile, stage/Dockerfile
Reverts hackforla/CivicTechJobs#460
- https://github.com/hackforla/CivicTechJobs/actions/runs/6594374726/job/17918187821#step:5:410
=> Revert "457 deployment bug in staging"

frontend/src/index.tsx, frontend/src/pages/LandingPage/LandingPageCop.tsx, frontend/src/pages/LandingPage/LandingPageIntro.tsx, frontend/tailwind.config.js
Fixes #
- Reordered imports in frontend/src/index.tsx
- Added LadingPage to tailwind config file
- Added Tailwind classes to elements on LandingPage
<details>
<summary>Old Mobile</summary>
<br>
<br>
</details>
<details>
<summary>New Mobile</summary>
<br>
<br>
</details>
<details>
<summary>Old Desktop</summary>
<br>
<br>
</details>
<details>
<summary>New Desktop</summary>
<br>
<br>
</details>
=> Fixed styles on LandingPage using TW classes

frontend/src/components/Inputs/Chip.tsx, frontend/src/pages/Authentication/LoginForm.tsx, frontend/src/pages/QualifierPage/QualifierComponents.tsx, frontend/src/pages/QualifierPage/QualifierPageRoles.tsx, frontend/src/tw-components/HeaderNav.tsx
Fixes #470
- Fixed spacing on the qualifier roles page
- Made navbar look like figma designs with more space around the logo and nav links
<details>
<summary>Before & Afters</summary>
</details>
=> Fix style inconsistencies

.github/linters/.stylelintrc.json, .github/workflows/linter.yml, .github/workflows/mkdocs-build.yml, mkdocs/docs/developer/frontend.md
Fixes #456
- Added setuptools installation in mkdocs-build.yml 
The first attempt to fix the mkdocs bug resolved the error complaining about missing "mkdocs-config" module, but got a new error about missing "setuptools module" so I added the installation of setuptools in the mkdocs-build.yml file
=> Fix mkdocs bug

.github/workflows/jest-react-test.yml, backend/config/settings.py, backend/server/urls.py, backend/server/views.py
Fixes #523
- Updated the healthcheck view to include uptime and version in response
- Edited healthcheck path in urls
=> Added healthcheck endpoint to API

docker-compose.dev.yml
Fixes # //not an issue, fixed minor error
- Corrected the name pattern for docker-compose-dev.yml to avoid docker compose up error
=> fixed name pattern

.github/ISSUE_TEMPLATE/Dev Onboarding
Hi there! Creating this template to aid in the onboarding of new devs to the team.
Fixes #
-
-
-
<details>
<br>
<br>
</details>
=> Create Dev Onboarding

docs/joining-the-team/web-developer.md
Fixes #
Using this to test the mkdocs deployment.
There is a github action for deploying changes to the docs in the develop branch. I believe this is what is currently deployed to https://hackforla.github.io/CivicTechJobs
Fixed some links in: https://hackforla.github.io/CivicTechJobs/joining-the-team/web-developer/
-
-
-
<details>
<br>
<br>
</details>
=> Test mkdocs deployment

.dockerignore, backend/.dockerignore, backend/backend/settings.py, dev/dev.env.example, dev/django.dockerfile, docker-compose.yml, frontend/.dockerignore, stage/Dockerfile
Fixes #
- fix dockerignore not ignoring select files in dev mode
- fix postgres container FATAL root user issue
- minor changes to dockerfile
=> Small docker stage fixes

.dockerignore, .gitignore
Fixes #
- Fix dockerignore not ignoring some files
- git should ignore schema.yml
=> minor dockerignore fixes

mkdocs/docs/developer/git-branch-structure.md, mkdocs/docs/developer/installation.md, mkdocs/docs/developer/mkdocs-architecture.md, mkdocs/docs/developer/mkdocs-edit-instructions.md, mkdocs/mkdocs.yml
Fixes #598, #610
- moved `docker --watch` note to FAQs in installation instructions
- Updated documentation about mkdocs
- Wrote documentation about `main` and `develop` branches and git branching workflow
=> Update documentation - git branch workflow

backend/backend/views.py, mkdocs/docs/developer/backend.md, mkdocs/docs/developer/devops.md
Fixes #
- Update Backend architecture documentation
- Update devops documentation
- Include documentation about how the stage environment is set up in docker
=> Update Documentation: backend architecture

frontend/src/pages/Demo/DemoTailwind.tsx, frontend/src/tw-components/Typography.tsx
- Added reusable `Typography` components with Tailwind in `tw-components/Typography.tsx`
- Created a div in `DemoTailwind.tsx` to preview typography styles in development
<details>
<summary>Tailwind Typography Components Demo</summary>
<br>
<br>
</details>
=> Add Typography Components (Tailwind Migration)

frontend/src/assets/images/images.tsx, frontend/src/components/Carousel/ClickCarousel.tsx, frontend/src/components/Carousel/ScrollCarousel.tsx, frontend/src/components/Dialog/Dialog.tsx, frontend/src/components/Inputs/Calendar.tsx, frontend/src/components/Inputs/Checkbox.tsx, frontend/src/components/Inputs/Dropdown.tsx, frontend/src/components/Inputs/ProtoInput.tsx, frontend/src/components/Notification/Notification.tsx, frontend/src/components/Scroll/ChevronScroll.tsx, frontend/src/components/Transition/Wrapper.tsx, frontend/src/components/Utility/hooks/dragToSelectUnselect.ts, frontend/src/components/Utility/utils.ts, frontend/src/pages/CreditsPage/CreditsPage.tsx, frontend/src/pages/Demo/Demo.tsx, frontend/src/tw-components/AuthNav.tsx, frontend/src/tw-components/CookieBanner.tsx, frontend/src/tw-components/StandardCard.tsx, frontend/src/tw-components/TextField.tsx
Fixes #609 
Resolved 33 ESLint syntax errors to improve code quality and maintainabilty. No functional changes, just syntax fixes. 
- Enhanced TypeScript typings for better type safety and clarity. 
- Improved prop validations by integrating PropTypes and TypeScript interfaces.
- Refactored functions, interfaces, and event handlers to use explicit types, eliminating any.
Notes:
- Some ESLint rules were selectively disabled with inline comments to accommodate ongoing development and pending design reviews.
- There was an error due to conflicting Tailwind CSS rules. I temporarily disabled the linter for this issue, but it might be worth checking with the UX team to determine the appropriate styling approach.
<details>
<br>
<br>
</details>
=> Fixed ESLint syntax errors across frontend

.github/workflows/deploy-stage.yml
Fixes #
- push CTJ stage Dockerfile image to ECR
=> push stage Dockerfile image to ECR

.github/workflows/deploy-stage.yml
Finished the Github Action to complete the CTJ Incubator Pipeline
- added the ECS restart action, so the ECS-fargate service will restart whenever code is pushed
- Changed IMAGE_TAG from "dev" to "stage" since that is the expected tag in the ECS task definition
- edited the name of the action displayed in the github Actions tab
NOTE: need to change our stage.env file to match the username, db name, etc from the terraform resource created in this [incubator PR](https://github.com/hackforla/incubator/pull/102)
=> added ECS redeployment step, edited IMAGE_TAG, changed action name

frontend/package-lock.json, frontend/src/pages/Demo/Demo.tsx
Test AWS deployment pipeline
- Npm audit
- merge main into develop
- test stage deployment
=> Develop into main
